version: '3.7'

services:
  app:
    image: fireflyiii/core:latest
    env_file:
      - .env
    ports:
      - "${PORT_APP}:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .db.env
    volumes:
      # - db_data:/var/lib/postgresql/data
      - /srv/volumes/fireflyiii-${ESTANCIA}/db/_data:/var/lib/postgresql/data

  cron:
    image: alpine
    command: sh -c "echo '*/1 * * * * wget -qO- http://fireflyiii:${PORT_APP}/api/v1/cron/${APP_KEY}' | crontab - && crond -f -L /dev/stdout"
    depends_on:
      - app


