version: '3.6'

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    # container_name: firefly-core
    restart: always
    volumes:
      # - firefly-upload:/var/www/html/storage/upload
      - /srv/volumes/fireflyiii/upload/_data:/var/www/html/storage/upload
    networks:
      - fireflayiii
    ports:
      - "8082:8080"
    depends_on:
      - db

  db:
    image: mariadb
    hostname: db
    # container_name: firefly-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: firefly
      # MYSQL_USER: firefly
      MYSQL_USER: admin
      # MYSQL_PASSWORD: fireflypassword
      MYSQL_PASSWORD: adm999
    volumes:
      - /srv/volumes/fireflyiii/db/_data:/var/lib/mysql
    networks:
      - fireflayiii

  cron:
    image: alpine
    restart: always
    # container_name: firefly-cron
    networks:
      - fireflayiii
    command: sh -c "echo '0 3 * * * wget -qO- /dev/null http://app:8082/api/v1/cron/75TureMC9GxQ9frXbRnLehbmdKWJAejh' | crontab - && crond -f -L /dev/stdout"

networks:
  fireflayiii:
    driver: bridge